### ISSUE TITLE
Can't access Extend and search to enable Devel Generate

### ISSUE THREAD

**Issue by nickausten-salsa** [govcms-training/site-builder#38]

**Comment by klonos** [comment]
This should now be fixed with https://projects.govcms.gov.au/GovCMS/govcms-training/-/commit/d93bd1e0c56c5b21cf9e3d5e5777bcc64242c56d

The Devel Generate module was already enabled before, but I have now also allowed access to the module management and permissions pages via the module_permissions module (not all modules/permissions can be managed - only those included in the allow list specified/curated by Finance).

Can you please confirm and close this issue @nickausten-salsa? Thanks

**Comment by nickausten-salsa** [comment]
I can now access > Extend thanks!
